spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:schlib.db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect

  main:
    web-application-type: none